
package artifacts_new;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyNewWebService", targetNamespace = "http://wsn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyNewWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<artifacts_new.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByCategory", targetNamespace = "http://wsn/", className = "artifacts_new.GetBookByCategory")
    @ResponseWrapper(localName = "getBookByCategoryResponse", targetNamespace = "http://wsn/", className = "artifacts_new.GetBookByCategoryResponse")
    public List<Book> getBookByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookTitlesByAuthor", targetNamespace = "http://wsn/", className = "artifacts_new.GetBookTitlesByAuthor")
    @ResponseWrapper(localName = "getBookTitlesByAuthorResponse", targetNamespace = "http://wsn/", className = "artifacts_new.GetBookTitlesByAuthorResponse")
    public List<String> getBookTitlesByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<artifacts_new.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByRatingAndNumRatings", targetNamespace = "http://wsn/", className = "artifacts_new.GetBooksByRatingAndNumRatings")
    @ResponseWrapper(localName = "getBooksByRatingAndNumRatingsResponse", targetNamespace = "http://wsn/", className = "artifacts_new.GetBooksByRatingAndNumRatingsResponse")
    public List<Book> getBooksByRatingAndNumRatings(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumBooksByPublisherAndCategories", targetNamespace = "http://wsn/", className = "artifacts_new.GetNumBooksByPublisherAndCategories")
    @ResponseWrapper(localName = "getNumBooksByPublisherAndCategoriesResponse", targetNamespace = "http://wsn/", className = "artifacts_new.GetNumBooksByPublisherAndCategoriesResponse")
    public String getNumBooksByPublisherAndCategories(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvgRatingByPublisher", targetNamespace = "http://wsn/", className = "artifacts_new.GetAvgRatingByPublisher")
    @ResponseWrapper(localName = "getAvgRatingByPublisherResponse", targetNamespace = "http://wsn/", className = "artifacts_new.GetAvgRatingByPublisherResponse")
    public String getAvgRatingByPublisher(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
