
package artifacts_new;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyNewWebServiceService", targetNamespace = "http://wsn/", wsdlLocation = "http://localhost:8080/WSNew-work2/MyNewWebService?wsdl")
public class MyNewWebServiceService
    extends Service
{

    private final static URL MYNEWWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MYNEWWEBSERVICESERVICE_EXCEPTION;
    private final static QName MYNEWWEBSERVICESERVICE_QNAME = new QName("http://wsn/", "MyNewWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSNew-work2/MyNewWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYNEWWEBSERVICESERVICE_WSDL_LOCATION = url;
        MYNEWWEBSERVICESERVICE_EXCEPTION = e;
    }

    public MyNewWebServiceService() {
        super(__getWsdlLocation(), MYNEWWEBSERVICESERVICE_QNAME);
    }

    public MyNewWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYNEWWEBSERVICESERVICE_QNAME, features);
    }

    public MyNewWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, MYNEWWEBSERVICESERVICE_QNAME);
    }

    public MyNewWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYNEWWEBSERVICESERVICE_QNAME, features);
    }

    public MyNewWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyNewWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyNewWebService
     */
    @WebEndpoint(name = "MyNewWebServicePort")
    public MyNewWebService getMyNewWebServicePort() {
        return super.getPort(new QName("http://wsn/", "MyNewWebServicePort"), MyNewWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyNewWebService
     */
    @WebEndpoint(name = "MyNewWebServicePort")
    public MyNewWebService getMyNewWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsn/", "MyNewWebServicePort"), MyNewWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYNEWWEBSERVICESERVICE_EXCEPTION!= null) {
            throw MYNEWWEBSERVICESERVICE_EXCEPTION;
        }
        return MYNEWWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
